# Uncomment this line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

def import_pods
    pod 'SQLite.swift', '~> 0.11.0'
    pod 'SubwayStations'
    pod "GTFSStations", :path => "../"
end

target 'GTFS Stations' do
    import_pods
end

target 'GTFS StationsTests' do
    import_pods
    pod 'Quick'
    pod 'Nimble'
end
