# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
use_frameworks!

target 'GTFS Stations' do
    pod 'SQLite.swift', git: 'https://github.com/stephencelis/SQLite.swift.git', branch: 'swift-2'
    pod "GTFSStations", :path => "../"
end

target 'GTFS StationsTests' do
    pod 'Quick', '~> 0.6.0'
    pod 'Nimble', '~> 2.0.0-rc.3'
end

