# Uncomment this line to define a global platform for your project
platform :ios, '7.0'
use_frameworks!

target 'GTFS Stations' do
    pod "GTFSStations", :path => "../"
end

target 'GTFS StationsTests' do
    pod 'Quick', '~> 0.3.1'
    pod 'Nimble', '~> 1.0.0'
end

