# reference: http://www.objc.io/issue-6/travis-ci.html

language: swift
osx_image: xcode10.1
before_install: 
  - gem install cocoapods
  - if brew outdated | grep -qx xctool; then brew upgrade xctool; fi
  - cd Example
  - pod update
  - cd ..
xcode_workspace: Example/GTFS Stations.xcworkspace 
xcode_scheme: GTFS Stations
xcode_sdk: iphonesimulator12.1
